// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKVnsz2nu3-EULR9iX1l_ehbdVm7a74P4',
    appId: '1:602359993946:web:9eb69c0f246b045dce6a63',
    messagingSenderId: '602359993946',
    projectId: 'excel-notification',
    authDomain: 'excel-notification.firebaseapp.com',
    storageBucket: 'excel-notification.appspot.com',
    measurementId: 'G-FELVWCKNS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX_91EyrsxB353OxoE5ek1my1pwe8AE2U',
    appId: '1:602359993946:android:08bc044975991ecbce6a63',
    messagingSenderId: '602359993946',
    projectId: 'excel-notification',
    storageBucket: 'excel-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9z-J27upKC-7RROxiy62-jJL13QwVYOw',
    appId: '1:602359993946:ios:1ae0307d8ea08bc8ce6a63',
    messagingSenderId: '602359993946',
    projectId: 'excel-notification',
    storageBucket: 'excel-notification.appspot.com',
    iosClientId: '602359993946-mg5gu6ii548njtq394r823cobphkh6pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.excel2022',
  );
}
