import 'package:excelapp/Models/event_card.dart';

var CompetitionsData = [
  Event(
    id: 1,
    name: 'Wave Cloning',
    icon: 'assets/icons/even_sample.png',
    desc: 'Lorem ipsum dolor sit amet, conse ctetur adi piscing elit.',
    category: 'CS-Tech',
    date: "27 Oct 2022",
    isCompetition: true,
  ),
  Event(
    id: 2,
    name: 'Game Plan',
    icon: 'assets/icons/even_sample.png',
    desc: 'Lorem ipsum dolor sit amet, conse ctetur adi piscing elit.',
    category: 'CS-Tech',
    date: "27 Oct 2022",
    isCompetition: true,
  ),
  Event(
    id: 3,
    name: 'Third Eye Photography',
    icon: 'assets/icons/even_sample.png',
    desc: 'Lorem ipsum dolor sit amet, conse ctetur adi piscing elit.',
    category: 'Gen-Tech',
    date: "27 Oct 2022",
    isCompetition: true,
  ),
  Event(
    id: 4,
    name: 'Valorant: GameZone',
    icon: 'assets/icons/even_sample.png',
    desc: 'Lorem ipsum dolor sit amet, conse ctetur adi piscing elit.',
    category: 'Non-Tech',
    date: "27 Oct 2022",
    isCompetition: true,
  ),
  Event(
    id: 5,
    name: 'Issue!',
    icon: 'assets/icons/even_sample.png',
    desc: 'Lorem ipsum dolor sit amet, conse ctetur adi piscing elit.',
    category: 'Workshops',
    date: "27 Oct 2022",
    isCompetition: false,
  ),
  Event(
    id: 6,
    name: 'Cloud Computing Workshop',
    icon: 'assets/icons/even_sample.png',
    desc: 'Lorem ipsum dolor sit amet, conse ctetur adi piscing elit.',
    category: 'Talks',
    date: "27 Oct 2022",
    isCompetition: false,
  ),
  Event(
    id: 7,
    name: 'Lifeline',
    icon: 'assets/icons/even_sample.png',
    desc: 'Lorem ipsum dolor sit amet, conse ctetur adi piscing elit.',
    category: 'General',
    date: "27 Oct 2022",
    isCompetition: false,
  ),
  Event(
    id: 8,
    name: 'Short Film Festival',
    icon: 'assets/icons/even_sample.png',
    desc: 'Lorem ipsum dolor sit amet, conse ctetur adi piscing elit.',
    category: 'General',
    date: "27 Oct 2022",
    isCompetition: false,
  ),
];
