import 'package:excelapp/Models/event_card.dart';

var CompetitionsData = [
  Event(
    id: 1,
    name: 'Wave Cloning',
    icon: 'https://www.iconpacks.net/icons/1/free-settings-icon-778-thumb.png',
    eventType: 'Offline',
    category: 'CS-Tech',
    datetime: "27 Oct 2022",
    isCompetition: true,
  ),
  Event(
    id: 2,
    name: 'Game Plan',
    icon: 'https://www.iconpacks.net/icons/1/free-settings-icon-778-thumb.png',
    eventType: 'Offline',
    category: 'CS-Tech',
    datetime: "27 Oct 2022",
    isCompetition: true,
  ),
  Event(
    id: 3,
    name: 'Third Eye Photography',
    icon: 'https://www.iconpacks.net/icons/1/free-settings-icon-778-thumb.png',
    eventType: 'Offline',
    category: 'Gen-Tech',
    datetime: "27 Oct 2022",
    isCompetition: true,
  ),
  Event(
    id: 4,
    name: 'Valorant: GameZone',
    icon: 'https://www.iconpacks.net/icons/1/free-settings-icon-778-thumb.png',
    eventType: 'Offline',
    category: 'Non-Tech',
    datetime: "27 Oct 2022",
    isCompetition: true,
  ),
  Event(
    id: 5,
    name: 'Issue!',
    icon: 'https://www.iconpacks.net/icons/1/free-settings-icon-778-thumb.png',
    eventType: 'Offline',
    category: 'Workshops',
    datetime: "27 Oct 2022",
    isCompetition: false,
  ),
  Event(
    id: 6,
    name: 'Cloud Computing Workshop',
    icon: 'https://www.iconpacks.net/icons/1/free-settings-icon-778-thumb.png',
    eventType: 'Offline',
    category: 'Talks',
    datetime: "27 Oct 2022",
    isCompetition: false,
  ),
  Event(
    id: 7,
    name: 'Talks',
    icon: 'https://www.iconpacks.net/icons/1/free-settings-icon-778-thumb.png',
    eventType: 'Offline',
    category: 'General',
    datetime: "27 Oct 2022",
    isCompetition: false,
  ),
  Event(
    id: 8,
    name: 'Short Film Festival',
    icon: 'https://www.iconpacks.net/icons/1/free-settings-icon-778-thumb.png',
    eventType: 'General',
    category: 'General',
    datetime: "27 Oct 2022",
    isCompetition: false,
  ),
];
